cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    # 127.0.0.1:8000/cart
    path('', detail, name='detail'), 

    # 127.0.0.1:8000/cart/add/2
    path('add/<int:product_id>/', add, name='product_add'),

    # 127.0.0.1:8000/cart/remove/2
    path('remove/<int:product_id>/', remove, name='product_remove'),
] 

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),
]

coupon/urls.py
from django.urls import path
from .views import add_coupon

app_name = 'coupon'

urlpatterns = [
    # 127.0.0.1:8000/coupon --> ?? --> config/urls.py <-- 1차 url
    # 127.0.0.1:8000/coupon/add/
    path('add/', add_coupon, name='add'),
]

order/urls.py
from django.urls import path 
from .views import *

# 여기는 order 앱 url 구성하는 페이지
# 2차 url 연결하면,
# 루트에 1차 url도 연결해야 함 (config 폴더의 urls.py 연결)

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('create_ajax', OrderCreateAjaxView.as_view(), name='order_create_ajax'),
    path('checkout/', OrderCheckoutAjaxView.as_view(), name='order_checkout'),
    path('validation/', OrderImpAjaxView.as_view(), name='order_validation'),
    path('complete/', order_complete, name='order_complete'),
        # 커스텀 관리자 페이지 임시 추가
    path('order_detail/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
    path('order_pdf/<int:order_id>/', admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', product_in_category, name='product_all'),
    #path('<slug:category_slug>/', product_in_category, name='product_in_category'),
    path(r'^(?P<category_slug>[-\S]+)/$', product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
    
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

class AddProductForm(forms.Form):
    quantity = forms.IntegerField()
    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product 
from .forms import AddProductForm
from .cart import Cart 
from coupon.forms import AddCouponForm

# Create your views here.
@require_POST
def add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = AddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product, 
            quantity=cd['quantity'], 
            is_update=cd['is_update']
        )
    return redirect('cart:detail')

def remove(request, product_id):
    print('test start')
    cart = Cart(request)
    print('test end')
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')

def detail(request):
    cart = Cart(request)
    add_coupon = AddCouponForm()

    for product in cart:
        product['quantity_form'] = AddProductForm(
            initial = {
                'quantity': product['quantity'],
                'is_update': True
            }

        )
    
    context = {
        'cart': cart,
        'add_coupon': add_coupon,
    }

    #return render('cart/detail.html', context) 
    return render(request, 'cart/detail.html', context) 

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}장바구니{%endblock%}

{% block content %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">상품 이미지(Image)</th>
                <th scope="col">제품(Product)</th>
                <th scope="col">수량(Quantity)</th>
                <th scope="col">삭제(Delete)</th>
                <th scope="col">단가(Unit Price)</th>
                <th scope="col">금액(Price)</th>
            </tr>
        </thead>

        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <th scope="row">
                            <a href="{{product.get_absolute_url}}">
                                <img src="{{product.image.url}}" class="img-thumbnail">
                            </a>
                        </th>
                        <td>
                            {{product.name}}
                        </td>
                        <td>
                            <form action="{% url 'cart:product_add' product.id %}" method="POST">
                                {{item.quantity_form.quantity}}
                                {{item.quantity_form.is_update}}
                                <input type="submit" class="btn btn-primary sm" value="업데이트">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td>
                            <a href="{% url 'cart:product_remove' product.id %}">삭제</a>
                        </td>
                        <td class="num">
                            {{item.price}}
                        </td>
                        <td class="'num">
                            {{item.total_price}}
                        </td>
                    </tr>
                {% endwith %}
            {% endfor %}

            {% if cart.coupon %}
                    <tr class="subtotal">
                        <td>Subtotal</td>
                        <td colspan="4"></td>
                        <td>{{cart.get_product_total}}원</td>
                    </tr>
                    
                    <tr>
                        <td>"{{cart.coupon.code}}" Coupon ({{cart.coupon.amount}}원)</td>
                        <td>- ${{cart.get_discount_total|floatformat:"2"}}</td>
                    </tr>
            {% endif %}


            <tr class="total">
                <td>합계</td>
                <td colspan="4"></td>
                <td>${{cart.get_total_price|floatformat:'2'}}</td>
            </tr>
        </tbody>
    </table>


    <p>
        쿠폰 추가:
    </p>

    <p>
        <form action="{% url 'coupon:add' %}" method="POST">
            {{add_coupon}}
            <input type="submit" value="추가하기">
            {% csrf_token %}
        </form>
    </p>    

    <p class="text-right">
        <a href="{% url 'shop:product_all' %}" class="btn btn-secondary">
            쇼핑 계속하기
        </a>
        <a href="{% url 'orders:order_create' %}" class="btn btn-secondary">
            계산하기
        </a>
    </p>

    <p class="text-right">
        
    </p>


{% endblock %}