cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    # 127.0.0.1:8000/cart
    path('', detail, name='detail'), 

    # 127.0.0.1:8000/cart/add/2
    path('add/<int:product_id>/', add, name='product_add'),

    # 127.0.0.1:8000/cart/remove/2
    path('remove/<int:product_id>/', remove, name='product_remove'),
] 

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),
]

shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', product_in_category, name='product_all'),
    #path('<slug:category_slug>/', product_in_category, name='product_in_category'),
    path(r'^(?P<category_slug>[-\S]+)/$', product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
    
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
    </script>

    
    {% block script %}
    {% endblock %}
    
    {% block style %}
    {% endblock %}    
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Django Shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav justify-content-end">
                <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'shop:product_all' %}">Product</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'cart:detail' %}">Cart
                    {% if cart|length > 0 %}
                        ${{cart.get_product_total}} with {{cart|length}} items
                    {% else %}
                        : Empty
                    {% endif %}
                </a>
                </li>

                <!-- login icon -->
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'account_logout' %}">로그아웃</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'account_login' %}">로그인</a>
                    {% endif %}
                </li>

            </ul>


        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="원하시는 상품명" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">상품검색</button>
            </form>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>